stages:
  - test
  - build
  - package
  - deploy

default:
  interruptible: true

variables:
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2

frontend_test:
  stage: test
  image: node:20-alpine
  script:
    - npm ci
    - npm test

frontend_build:
  stage: build
  image: node:20-alpine
  needs: ["frontend_test"]
  script:
    - npm ci
    - npm run lint
    - npm run build

frontend_docker_build_push:
  stage: package
  image: docker:27.1.1
  services:
    - docker:27.1.1-dind
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t "$FRONTEND_IMAGE:$CI_COMMIT_SHA" -f Dockerfile .
    - docker tag "$FRONTEND_IMAGE:$CI_COMMIT_SHA" "$FRONTEND_IMAGE:latest"
    - docker push "$FRONTEND_IMAGE:$CI_COMMIT_SHA"
    - docker push "$FRONTEND_IMAGE:latest"

deploy:
  stage: deploy
  script:
    - echo "Deploy step here (e.g. SSH to server and pull Docker image)"